{% set version = "4.7.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mbess
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MBESS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MBESS/MBESS_{{ version }}.tar.gz
  sha256: afb3858596f5485c5c7e6b72fee37be01576f80e93d4fbed6f38c4e3f3c153b5

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-openmx
    - r-boot
    - r-gsl
    - r-lavaan
    - r-mnormt
    - r-nlme
    - r-sem
    - r-semtools
  run:
    - r-base
    - r-mass
    - r-openmx
    - r-boot
    - r-gsl
    - r-lavaan
    - r-mnormt
    - r-nlme
    - r-sem
    - r-semtools

test:
  commands:
    - $R -e "library('MBESS')"           # [not win]
    - "\"%R%\" -e \"library('MBESS')\""  # [win]

about:
  home: http://nd.edu/~kkelley/site/MBESS.html
  license: GPL-2 | GPL-3
  summary: Implements methods that useful in designing research studies and analyzing data, with  particular emphasis on methods that are developed for or used within the behavioral,  educational, and social sciences (broadly defined). That being said, many of the methods  implemented within MBESS are applicable to a wide
    variety of disciplines. MBESS has a  suite of functions for a variety of related topics, such as effect sizes, confidence intervals  for effect sizes (including standardized effect sizes and noncentral effect sizes), sample size planning (from the accuracy in parameter estimation [AIPE], power analytic, equivalence,
    and  minimum-risk point estimation perspectives), mediation analysis, various properties of  distributions, and a variety of utility functions. MBESS (pronounced 'em-bes') was originally  an acronym for 'Methods for the Behavioral, Educational, and Social Sciences,' but at this  point MBESS contains methods applicable
    and used in a wide variety of fields and is an  orphan acronym, in the sense that what was an acronym is now literally its name. MBESS has  greatly benefited from others, see <http://nd.edu/~kkelley/site/MBESS.html> for a detailed  list of those that have contributed and other details.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: MBESS
# Type: Package
# Title: The MBESS R Package
# Version: 4.5.1
# Date: 2019-5-17
# Authors@R: c(person("Ken", "Kelley", role=c("aut", "cre"), email="kkelley@nd.edu"))
# Maintainer: Ken Kelley <kkelley@nd.edu>
# Depends: R (>= 3.2.0), stats
# Imports: boot, gsl, lavaan, MASS, methods, mnormt, nlme, OpenMx, parallel, sem, semTools
# Description: Implements methods that useful in designing research studies and analyzing data, with  particular emphasis on methods that are developed for or used within the behavioral,  educational, and social sciences (broadly defined). That being said, many of the methods  implemented within MBESS are applicable to a wide variety of disciplines. MBESS has a  suite of functions for a variety of related topics, such as effect sizes, confidence intervals  for effect sizes (including standardized effect sizes and noncentral effect sizes), sample size planning (from the accuracy in parameter estimation [AIPE], power analytic, equivalence, and  minimum-risk point estimation perspectives), mediation analysis, various properties of  distributions, and a variety of utility functions. MBESS (pronounced 'em-bes') was originally  an acronym for 'Methods for the Behavioral, Educational, and Social Sciences,' but at this  point MBESS contains methods applicable and used in a wide variety of fields and is an  orphan acronym, in the sense that what was an acronym is now literally its name. MBESS has  greatly benefited from others, see <http://nd.edu/~kkelley/site/MBESS.html> for a detailed  list of those that have contributed and other details.
# License: GPL-2 | GPL-3
# URL: http://nd.edu/~kkelley/site/MBESS.html
# RoxygenNote: 6.0.0
# NeedsCompilation: no
# Packaged: 2019-05-17 10:33:01 UTC; kkelley
# Author: Ken Kelley [aut, cre]
# Repository: CRAN
# Date/Publication: 2019-05-17 13:40:13 UTC
