appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: djjDKMGnJPPcEhpuDoDcj6LN7Wzs7+U3otzHx08+0RqE2pAylZ3VmYn8oPAkbvQRcpXnZdXcF2RJBA+RySRjEYqZ/Gm8nMA7MjInfExcx3mFA9gEu1YBUjwM48CrEWGTSOE5hqFV2wcP8Azx7CXVYEGL7LGlBVcLbCvrYddVT6IqMhCHgru9LhGIzVj2HoXEMG+BcLrhHdXDSj1u9x6703pYn54SELHa6BlNrEjo0ySNVCOHGNEfXCLWFo1ofFeE2+If0Ko5Ga8ntUQLCHnaB66Irc7UrkLX7lFQzQ/Io/LEqP9Z03yQPTqJJTVgYytgolOs7wpIn1huz1+iZHVUBAM/lCJwkOxjMIAgemxP5XZbr4rFrqcjlm1Y8LUNH4KFk5XQzzhRVS8Ioj9yjPJpG9ixvm5S+GGczfJ+1GZCZA1OAAbZkstLuNrGwxpfshH04EM3joz/JlqBzdluU/yBnXkrHoRt59vsm45Z3+Meeh2SAiHmFufXTroGXVy0cCgPKDq5qRIptdNFoclLW9qcDTJ3W73MeMYbY36D9eeI45PZsbLrKw1vWYHL4YQ6X/RooN4pkmq0FTGamBuuVJQ9+uDSeox1hxSHHqL+LBCdICftV1VQEFLJmp3tOxSc+cd8RYNsRGyAit6HrE3OtAH4OCrgnQvWc6XndeahpP8dypM=
conda_forge_output_validation: true
