travis:
  secure:
    BINSTAR_TOKEN: AxWDT+gsC4gIqwcskOcEZ2qb+WJJUIdqtqusrXKPzi7simgQOy9va4k9VEcOv1Kt6of5b07gdpgGIoDYOg9Dp6i4sqVIXMFqJRHarRAT4T5+Cx33FCT2YGuLnWaEO0fQHHwkEah3STWFnBjgAx30sE/xd2brBUGu4AapwKQltCPfNF8TwgVlclDtOb65mGgxILIHHquCz0IAGBRtPTgpmQ2yx5Ot2zKSxqL8YkWVGS1+jgPFSZN1zIb3UbmCxyhH1GCcqZmY+iVeQQQTeJU+UG8tOU4XHmsfJgzw72ToYH67z5GI4Zx3nMaxQoUdB/nBqMY93yGg7JTgqZyFecy0grS0ptN0S27CO51kEga9/L7zQ6idrU1bZIcSvjr4QGLkMpIxDCN73XiciEGj7/lDFUpi4ZiuxMEC/MPG32XVbUgQuZENrogMjXX3f3BQOwDvgHkRSEH6QsE+/lauAEWQoTEFWCfFL9g5MzOrISgjix3RrEVUlVt1LNRz1FnxJr7aN7c79+SLqZ5G1u0rR3VPHrmQh2KT4cFZbPCRkDwk8mtubPF/Vp+e3mvNB76cFnex8yyq4l7u/HyM0RK56fj0UnWUbj+plt7b/JUZ6BxgmNtPKURFENmFueDXkMeYPv/wOptF1CxVPrYAmGwMMwCAF0GUDAnGOf+55t7vdJzPhaY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
